spring.application.name=panier-service
server.port=8082

# Configuración de H2 (Base de datos en memoria para el carrito)
spring.datasource.url=jdbc:h2:mem:panierdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true