version: '3.8'

services:
  gateway:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=8080
    networks:
      - microservices-network
    depends_on:
      - catalogue
      - panier
      - paiment
      - tracking

  catalogue:
    build: ./catalogue-service
    container_name: catalogue-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=catalogue-service
      - SERVER_PORT=8081
    networks:
      - microservices-network

  panier:
    build: ./panier-service
    container_name: panier-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=panier-service
      - SERVER_PORT=8082
    networks:
      - microservices-network
    depends_on:
      - catalogue
      - paiment

  paiment:
    build: ./paiment-service
    container_name: paiment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=paiment-service
      - SERVER_PORT=8083
    networks:
      - microservices-network
    depends_on:
      - catalogue

  tracking:
    build: ./tracking-service
    container_name: tracking-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=tracking-service
      - SERVER_PORT=8084
    networks:
      - microservices-network
    depends_on:
      - catalogue
      - paiment
      - panier

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - microservices-network
    depends_on:
      - gateway

networks:
  microservices-network:
    driver: bridge
