server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

        - id: panier-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/panier/**
          filters:
            - RewritePath=/api/panier/(?<segment>.*), /${segment}

        - id: paiement-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/paiement/**
          filters:
            - RewritePath=/api/paiement/(?<segment>.*), /api/${segment}

        - id: tracking-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/tracking/**
          filters:
            - RewritePath=/api/tracking/(?<segment>.*), /api/${segment}