spring.application.name=catalogue-service
server.port=8081
spring.datasource.url=jdbc:h2:mem:cataloguedb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.jpa.hibernate.ddl-auto=update